---

- name: Install Bind
  apt: name=bind9

- name: Make sure Bind zones directory exists
  file:
    dest: /etc/bind/zones
    state: directory

- name: Configure DNS
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
  with_items:
    - etc/bind/bad-hosts.conf
    - etc/bind/named.conf.local
    - etc/bind/zones/in-addr.arpa
    - etc/bind/zones/local.zone
  notify:
    - Restart BIND

- name: Add local host information
  with_items: "{{ internal_hosts }}"
  lineinfile:
    dest: /etc/bind/zones/local.zone
    state: present
    line: "{{ item.name }} IN A {{ internal_ip_octet_1 }}.{{ internal_ip_octet_2 }}.{{ internal_ip_octet_3 }}.{{ item.ip }}"

- name: Add local host information (IN ADDR ARPA)
  with_items: "{{ internal_hosts }}"
  lineinfile:
    dest: /etc/bind/zones/in-addr.arpa
    state: present
    line: "{{ item.ip }} IN PTR {{ item.name }}.{{ dns_domain }}."

